#!/usr/bin/env python3
"""
static_site_generator.py - Manual build step for michael.nekoweb.org

Run this BEFORE `git push` (the github workflow deploys public/ as-is):

    python3 static_site_generator.py

What it does
------------
* Converts the markdown in content/ into HTML: every content/**/*.md
  becomes public/**/*.html (same relative path), and each folder with
  articles gets a landing page public/<folder>.html listing them, so the
  sections appear in the sidebar like technical.html does. Pages that
  carry the "Generated by static_site_generator.py" marker are regenerated from the
  markdown on every run; hand-written pages in public/ are never touched,
  and generated pages whose markdown has been deleted are pruned.
* Scans every *.html file under public/, including subfolders, so the
  git structure and the webpage structure stay in sync.
* Builds a hierarchical sitemap from the folder structure. A page named
  <section>.html is treated as the landing page for the sibling folder
  <section>/, so pages inside technical/ are shown as children of
  technical.html, e.g.:

      Home (index.html)
      Cool stuff! (cool_stuff.html)
      Technical landing page (technical.html)
        Codecs (technical/codecs.html)

* Excludes special folders from the sitemap:
  - assets/  - assets only (images, music), never webpages
  - unlisted/ - secret pages you reach by typing the URL or exploring the
                site; they still get the sidebar, just no link to them.
  The 404 page (not_found.html) is also left out of the sitemap.
* Injects a fixed left-hand sidebar into every page (except inside assets/).
  The sidebar shows a compact music player (the Tamatown funky loop, native
  audio controls, never autoplays) above the sitemap, plus the sitemap, a
  sticker linking to nekoweb.org and a copyright notice. The page or section
  you are currently on is highlighted. Branches only expand when relevant:
  the home page shows just the top-level pages, and a section's second- and
  third-level pages appear once you are on that section or on a page inside
  it, so the sidebar stays compact as the site grows. Links are written
  relative to each page's own folder, so pages in subfolders get
  "../index.html" and so on.
  On phones (max-width 600px) the sidebar turns into a full-width top bar
  so the content gets the whole viewport.
* Wraps the body text of every page in a <main class="content-box"> element
  so the text sits on a cream panel centered in the viewport, with the
  background pattern visible all around it (styled in public/style.css).
  A page containing <!-- nocontentbox --> opts out of that wrapper so
  hand-crafted pages can control their own layout; the marker is honored in
  both directions (adding it unwraps, removing it re-wraps), and removing
  the marker converges back to the normal box. Like the sidebar, this is
  idempotent: re-running the build re-wraps the current box instead of
  nesting another one.

The script is idempotent: re-running it replaces any previously injected
sidebar instead of duplicating it, so it is safe to run after every edit.
If you add, rename or remove a page, just run the build again.

The injected markup is pure HTML + CSS. No JavaScript is used anywhere.
"""

import html as htmlmod
import pathlib
import posixpath
import re
import sys
from dataclasses import dataclass, field

ROOT = pathlib.Path(__file__).resolve().parent
PUBLIC = ROOT / "public"
CONTENT = ROOT / "content"

HOME_LABEL = "Home"
HOMEPAGE_FILE = "index.html"
NOT_FOUND_FILE = "not_found.html"

# Folders that are never listed in the sidebar sitemap.
EXCLUDE_FROM_SITEMAP = {"assets", "unlisted"}
# Folders whose pages do not even get a sidebar injected (pure assets).
EXCLUDE_FROM_INJECTION = {"assets"}

CSS_MARKER_START = "BEGINSIDEBAR:CSS"
CSS_MARKER_END = "ENDSIDEBAR:CSS"
SIDEBAR_MARKER_START = "BEGINSIDEBAR"
SIDEBAR_MARKER_END = "ENDSIDEBAR"

# A comment like this is the signature of a page generated from content/.
# The build regenerates or prunes generated pages, and refuses to overwrite
# a hand-written public/ page that lacks this marker.
GENERATED_RE = re.compile(
    r"<!--\s*Generated by static_site_generator\.py.*?-->", re.DOTALL
)

STICKER = (
    '<a href="https://nekoweb.org/">'
    '<img src="https://nekoweb.org/assets/buttons/button1.gif" '
    'width="88" height="31" alt="Nekoweb">'
    "</a>"
)
LINKEDIN_URL = "https://www.linkedin.com/in/michael-knapman/"
LINKEDIN_IMG = "assets/linkedin.webp"
COPYRIGHT = "Copyright © 2026 Michael Knapman. All Rights Reserved."

# Compact music player shown at the top of the sidebar. It uses the browser's
# native audio controls (play/pause + slider), so no JS is needed. It never
# autoplays; it loops once the visitor presses play. The src is written
# relative to each page's own folder, like every other asset reference.
MUSIC_FILE = "assets/TamaTown_Funky_V3_loop.mp3"
AUDIO_PLAYER = (
    '    <div class="sidebar-audio">\n'
    '        <p class="sidebar-audio-label">Now playing: Tamatown Theme</p>\n'
    '        <audio controls loop preload="metadata" src="{src}"></audio>\n'
    "    </div>\n"
)

SIDEBAR_CSS = """
/* Injected by static_site_generator.py - do not edit by hand, re-run the build instead. */
:root {
    --sidebar-width: 260px;
}
body {
    margin-left: var(--sidebar-width);
}
aside.sidebar {
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    width: var(--sidebar-width);
    box-sizing: border-box;
    overflow-y: auto;
    padding: 16px 14px;
    background-color: #f3f0ea;
    border-right: 1px solid #d8d2c6;
    font-family: sans-serif;
    font-size: 14px;
    z-index: 1000;
}
.sidebar-nav ul {
    list-style: none;
    margin: 0;
    padding: 0;
}
.sidebar-nav ul ul {
    padding-left: 14px;
}
.sidebar-nav li {
    margin: 6px 0;
}
.sidebar-nav li.group > span {
    display: block;
    padding: 4px 8px;
    font-size: 12px;
    letter-spacing: 0.5px;
    text-transform: uppercase;
    color: #8a8375;
}
.sidebar-nav a {
    display: block;
    padding: 7px 8px;
    line-height: 1.2;
    color: #224a77;
    text-decoration: none;
    border-radius: 4px;
}
.sidebar-nav a:hover,
.sidebar-nav a:focus {
    background-color: #e3dccb;
}
.sidebar-nav a.current {
    background-color: #d9d2c2;
    font-weight: bold;
    color: #17375c;
}
.sidebar-foot {
    margin-top: 24px;
    border-top: 1px solid #d8d2c6;
    padding-top: 12px;
    text-align: center;
}
.sidebar-foot p {
    margin: 8px 0 0;
    font-size: 12px;
    color: #6b6559;
}
/* Compact music player pinned to the top of the sidebar, above the sitemap.
   Native audio controls: play/pause + a small slider, no JS required. */
.sidebar-audio {
    margin-bottom: 14px;
    padding: 5px 6px 6px;
    background-color: #fdf6e3;
    border: 1px solid #d8d2c6;
    border-radius: 6px;
}
.sidebar-audio-label {
    margin: 0 0 4px;
    font-size: 10px;
    font-weight: bold;
    letter-spacing: 0.3px;
    color: #6b6559;
}
.sidebar-audio audio {
    display: block;
    width: 100%;
}
/* Mobile: the sidebar becomes a full-width top bar so the content gets
   the whole viewport. It sits in normal flow (scrolls away as you read)
   and scrolls internally if the sitemap outgrows the capped height. */
@media (max-width: 600px) {
    body {
        margin-left: 0;
    }
    aside.sidebar {
        position: static;
        width: 100%;
        height: auto;
        max-height: 32vh;
        overflow-y: auto;
        box-sizing: border-box;
        padding: 8px 10px 10px;
        border-right: none;
        border-bottom: 1px solid #d8d2c6;
    }
    .sidebar-nav ul {
        padding-left: 0;
    }
    .sidebar-nav ul ul {
        padding-left: 12px;
    }
    .sidebar-nav li {
        margin: 4px 0;
    }
    .sidebar-nav a {
        padding: 6px 6px;
        font-size: 13px;
    }
    .sidebar-foot {
        margin-top: 8px;
        padding-top: 8px;
    }
}
"""


@dataclass
class PageNode:
    """A clickable page in the sitemap."""

    rel_path: str  # posix path relative to PUBLIC, e.g. "technical/codecs.html"
    label: str
    children: list = field(default_factory=list)


@dataclass
class GroupNode:
    """A non-clickable section heading, used when a folder has no landing page."""

    label: str
    children: list = field(default_factory=list)


def escape_html(text):
    """Escape text so it is safe inside HTML markup and attributes."""
    return htmlmod.escape(text, quote=True)


def extract_title(html, filename):
    match = re.search(r"<title[^>]*>([^<]*)</title>", html, re.IGNORECASE)
    if match and match.group(1).strip():
        # Titles in <title> tags carry HTML entities; unescape so callers
        # can apply exactly one round of escaping for their own context.
        return htmlmod.unescape(match.group(1).strip())
    return filename.removesuffix(".html")


def parent_dir(rel_path):
    """Parent directory of a posix rel path, "" for the root folder."""
    return posixpath.dirname(rel_path)


def stem(rel_path):
    """File stem, e.g. "technical/codecs.html" -> "codecs"."""
    return posixpath.splitext(posixpath.basename(rel_path))[0]


def rel_href(cur_dir, target_rel_path):
    """Relative href from a page in cur_dir to a sitemap target."""
    if not cur_dir:
        return target_rel_path
    up = "../" * len(cur_dir.split("/"))
    return up + target_rel_path


class Sitemap:
    """Builds and holds the hierarchical sitemap for the whole site."""

    def __init__(self):
        self.pages = {}       # rel_path -> PageNode
        self.pages_in_dir = {}  # dir -> [rel_path, ...]
        self.all_dirs = set()   # every directory that contains a page below it

        self._scan_pages()
        self._index_dirs()
        self.root = self._build_tree("")

    def _is_excluded(self, rel_path):
        parts = rel_path.split("/")[:-1]
        return any(part in EXCLUDE_FROM_SITEMAP for part in parts)

    def _scan_pages(self):
        for path in sorted(PUBLIC.rglob("*.html")):
            rel = path.relative_to(PUBLIC).as_posix()
            if self._is_excluded(rel):
                continue
            if path.name == NOT_FOUND_FILE:
                continue
            label = (HOME_LABEL if rel == HOMEPAGE_FILE
                     else extract_title(path.read_text(encoding="utf-8"), path.name))
            self.pages[rel] = PageNode(rel, label)

    def _index_dirs(self):
        for rel in self.pages:
            d = parent_dir(rel)
            self.pages_in_dir.setdefault(d, []).append(rel)
            self.all_dirs.add(d)  # when rel's parent == "" we add "" directly
            while d:
                d = parent_dir(d)
                self.all_dirs.add(d)

    def _child_dirs_with_pages(self, cur_dir):
        """Immediate sub-folders of cur_dir that contain pages somewhere below."""
        found = set()
        prefix = f"{cur_dir}/" if cur_dir else ""
        for rel in self.pages:
            if rel.startswith(prefix):
                rest = rel[len(prefix):]
                if "/" in rest:
                    found.add(rest.split("/", 1)[0])
        return found

    def _build_tree(self, cur_dir):
        children = []
        my_pages = self.pages_in_dir.get(cur_dir, [])
        my_pages = sorted(my_pages, key=lambda rel: (rel != HOMEPAGE_FILE, stem(rel)))
        for rel in my_pages:
            node = self.pages[rel]
            section = stem(rel) if not cur_dir else posixpath.join(cur_dir, stem(rel))
            if section in self.all_dirs:
                node.children = self._build_tree(section)
            children.append(node)

        for sub in sorted(self._child_dirs_with_pages(cur_dir)):
            section = sub if not cur_dir else posixpath.join(cur_dir, sub)
            landing = f"{sub}.html" if not cur_dir else posixpath.join(cur_dir, sub + ".html")
            if landing not in self.pages:
                group = GroupNode(sub)
                group.children = self._build_tree(section)
                children.append(group)
        return children


def strip_block(text, start_token, end_token):
    """Remove a previously injected block (idempotency).

    The blocks this script writes own the single newline on each side, so
    both are consumed here and re-added on injection. Without that, blank
    lines would creep into the file on every run.
    """
    pattern = re.compile(
        r"\n?<!--\s*" + re.escape(start_token) + r"\s*-->.*?"
        r"<!--\s*" + re.escape(end_token) + r"\s*-->\n?",
        re.DOTALL,
    )
    return pattern.sub("", text)


def normalize_marker_spacing(html):
    """Normalize blank lines next to the injected blocks.

    Guarantees deterministic spacing at the block boundaries (the CSS marker
    sits on its own line, one blank line separates the sidebar footer from
    the page content) and cleans up blank-line runs left over from older
    static_site_generator versions. This is idempotent: on already-clean files it is a
    no-op.
    """
    # CSS block: exactly one newline before the opening marker. \s* (not
    # just \n*) so leftover indentation can never pile up extra newlines.
    html = re.sub(r"\s*(<!--\s*BEGINSIDEBAR:CSS\s*-->)", r"\n\1", html)
    # Sidebar block: exactly one blank line after the closing marker.
    html = re.sub(
        r"(<!--\s*ENDSIDEBAR\s*-->)(\n*)", r"\1\n\n", html
    )
    return html


CONTENT_BOX_OPEN = '<main class="content-box">'
CONTENT_BOX_CLOSE = "</main>"

# A page containing <!-- nocontentbox --> opts out of the central cream text
# box so it can control its own layout (e.g. a hand-crafted art shrine). The
# sidebar and stylesheet are still injected; only the wrapper is skipped.
NO_CONTENTBOX_MARKER = "nocontentbox"


def strip_content_box(content):
    """Remove a <main class="content-box">...</main> wrapper, if present.

    The wrapper can sit anywhere in the content region (a page may carry the
    opt-out marker or other comments before it). Returns the inner text with
    wrapper edges dropped; returns `content` unchanged when no wrapper found.
    """
    open_pos = content.find(CONTENT_BOX_OPEN)
    close_pos = content.rfind(CONTENT_BOX_CLOSE)
    if open_pos == -1 or close_pos == -1 or close_pos < open_pos:
        return content
    inner = content[open_pos + len(CONTENT_BOX_OPEN):close_pos].strip("\n")
    prefix = content[:open_pos].rstrip("\n")
    suffix = content[close_pos + len(CONTENT_BOX_CLOSE):].lstrip("\n")
    return (prefix + "\n" + inner + "\n" + suffix).strip("\n")


def wrap_content(html):
    """Wrap the page's body text in the central cream text box.

    Everything between the sidebar's closing marker and </body> becomes the
    inside of a <main class="content-box"> element. style.css centers the
    box and gives it its cream background, leaving the pattern visible on
    all four sides.

    Idempotent: a page that already carries the wrapper is left alone, so
    re-running the build never nests a second box. Pages that ask to opt out
    with <!-- nocontentbox --> are *unwrapped* instead, so toggling the
    marker in either direction always converges on the page being in the
    right state.
    """
    body_close = html.rfind("</body>")
    if body_close == -1:
        return html

    marker = f"<!-- {SIDEBAR_MARKER_END} -->"
    marker_end = html.rfind(marker)
    if marker_end == -1 or marker_end > body_close:
        return html

    content = html[marker_end + len(marker):body_close]

    if f"<!-- {NO_CONTENTBOX_MARKER} -->" in html:
        unwrapped = strip_content_box(content)
        if unwrapped is not content:
            return (html[:marker_end + len(marker)] + "\n"
                    + unwrapped + "\n" + html[body_close:])
        return html  # already unwrapped

    if CONTENT_BOX_OPEN in content:
        return html  # already wrapped

    wrapper = (
        f"\n{CONTENT_BOX_OPEN}\n"
        + content.strip("\n")
        + f"\n{CONTENT_BOX_CLOSE}\n"
    )
    return html[:marker_end + len(marker)] + wrapper + html[body_close:]


def is_node_active(node, current_rel):
    """True when the current page is this node or one of its descendants.

    This is what decides whether a branch is expanded in the sidebar: a
    section's sub-pages appear when you are on the section itself (its
    landing page) or on any page inside it, and stay hidden otherwise so
    the sidebar does not balloon on large sites.
    """
    if isinstance(node, PageNode):
        if current_rel == node.rel_path:
            return True
        section = posixpath.splitext(node.rel_path)[0]  # "technical.html" -> "technical"
    else:  # GroupNode: the branch is the folder with this label
        section = node.label
    return current_rel.startswith(section + "/")


def render_nav(nodes, cur_dir, current_rel, depth=0):
    """Render the nested <ul> sitemap. Handles page and group nodes.

    A branch is only expanded when is_node_active is true, i.e. the visitor
    is on that branch: the home page shows just the top level, and second/
    third-level pages appear once you are on the relevant section (or on a
    page inside it). Sub-pages are never a dead end, because every folder
    has a landing page that links to them.
    """
    out = []
    pad = "    " * (depth + 2)
    for node in nodes:
        if isinstance(node, PageNode):
            href = rel_href(cur_dir, node.rel_path)
            is_current = node.rel_path == current_rel
            extra = ' class="current" aria-current="page"' if is_current else ""
            link = (f"{pad}<li><a href=\"{href}\"{extra}>"
                    f"{escape_html(node.label)}</a>")
            if node.children and is_node_active(node, current_rel):
                # The child <ul> nests *inside* the <li> (a bare <ul> under
                # <ul> is invalid HTML and hurts screen readers).
                out.append(link)
                out.append(f"{pad}<ul>")
                out.extend(render_nav(node.children, cur_dir, current_rel, depth + 1))
                out.append(f"{pad}</ul></li>")
            else:
                out.append(link + "</li>")
        else:  # GroupNode
            head = (f"{pad}<li class=\"group\"><span>"
                    f"{escape_html(node.label)}</span>")
            if node.children and is_node_active(node, current_rel):
                out.append(head)
                out.append(f"{pad}<ul>")
                out.extend(render_nav(node.children, cur_dir, current_rel, depth + 1))
                out.append(f"{pad}</ul></li>")
            else:
                out.append(head + "</li>")
    return out


def build_sidebar(sitemap, current_rel):
    cur_dir = parent_dir(current_rel)
    nav_lines = render_nav(sitemap.root, cur_dir, current_rel)
    nav = "\n".join(nav_lines)
    linkedin = (
        f'<a href="{LINKEDIN_URL}">'
        f'<img src="{rel_href(cur_dir, LINKEDIN_IMG)}" '
        f'width="64" height="54" alt="LinkedIn">'
        "</a>"
    )
    return (
        f"\n<!-- {SIDEBAR_MARKER_START} -->\n"
        f'<aside class="sidebar">\n'
        + AUDIO_PLAYER.format(src=rel_href(cur_dir, MUSIC_FILE))
        + f"    <nav class=\"sidebar-nav\" aria-label=\"Sitemap\">\n"
        f"        <ul>\n"
        f"{nav}\n"
        f"        </ul>\n"
        f"    </nav>\n"
        f"    <div class=\"sidebar-foot\">\n"
        f"        {STICKER}\n"
        f"        {linkedin}\n"
        f"        <p>{escape_html(COPYRIGHT)}</p>\n"
        f"    </div>\n"
        f"</aside>\n"
        f"<!-- {SIDEBAR_MARKER_END} -->\n"
    )


def build_css_block(cur_dir):
    """The injected head block: favicon + inline site CSS + sidebar CSS.

    style.css is inlined rather than <link>ed because it is tiny: inlining
    removes a render-blocking network request (a PageSpeed recommendation).
    The inlined copy lives inside the page, so url(assets/...) references in
    it would resolve relative to the page's folder; they are rewritten to
    root-absolute /assets/... paths, which work from any page depth. The
    favicon link (also injected here) stops browsers from 404-ing on the
    default /favicon.ico request.
    """
    site_css = (PUBLIC / "style.css").read_text(encoding="utf-8")
    site_css = re.sub(r"url\(\s*assets/", "url(/assets/", site_css)
    return (
        f"<!-- {CSS_MARKER_START} -->\n"
        f'<link rel="icon" href="/favicon.ico">\n'
        f"<style id=\"site-css\">{site_css}</style>\n"
        f"<style id=\"sidebar-css\">{SIDEBAR_CSS}</style>\n"
        f"<!-- {CSS_MARKER_END} -->\n"
    )


DESCRIPTION_MAX = 158

# Curated meta descriptions for pages whose body text is not self-descriptive
# (landing pages with plain link lists, the home page, error/secret pages).
# Keys are paths relative to public/. Every other page gets an automatic
# description built from its own first paragraph.
PAGE_DESCRIPTIONS = {
    "index.html": (
        "Michael Knapman's personal corner of the web: enter TamaTown and click "
        "a building to explore selected works, short stories, shrines, Siivagunner "
        "lore and technical notes."
    ),
    "cool_stuff.html": (
        "Cool stuff Michael Knapman likes: quirky, interesting websites and fun "
        "links from around the web."
    ),
    "credits.html": (
        "Credits for michael.nekoweb.org: background art, the tools used to build "
        "the site, and the websites that inspired it."
    ),
    "selected-works.html": (
        "Works Michael Knapman admires: Capcom, Game Freak & the Pokémon Company, "
        "HAL Laboratory, Em Essex, Tim Follin and more."
    ),
    "short-story.html": (
        "Short stories and essays by Michael Knapman: an ode to adventure, the "
        "copper age collapse, maize, financial risks and more."
    ),
    "housekeeping.html": (
        "Housekeeping notes for michael.nekoweb.org: how this site is built, its "
        "AI use policy and inspiration."
    ),
    "siivagunner.html": (
        "A shrine to Siivagunner: the discovery story, a hall of fame of rips and "
        "lists of silly ideas."
    ),
    "shrines.html": (
        "Shrines: things Michael Knapman finds interesting, including Ken Sugimori "
        "and early Pokémon artwork."
    ),
    "shrines/ken-sugimori.html": (
        "A shrine to Ken Sugimori and his early Pokémon artwork: the hand-painted "
        "watercolor era of the original 151."
    ),
    "technical.html": (
        "Technical notes by Michael Knapman: video and audio codecs, ETFs, USB, "
        "Wi-Fi and toothbrushes."
    ),
    "not_found.html": (
        "404 - page not found on michael.nekoweb.org. Head back to the home page."
    ),
    "unlisted/boo.html": (
        "A spooky secret page hidden on Michael Knapman's website. Boo!"
    ),
}

META_DESC_RE = re.compile(
    r'<meta\s+name=["\']description["\']\s+content=["\'][^"]*["\']\s*/?>',
    re.IGNORECASE,
)


def escape_attr(text):
    """Escape text so it is safe inside a double-quoted HTML attribute."""
    return escape_html(text)


def auto_description(html, rel_path):
    """Build a meta description from the page's own first real paragraph.

    Only looks at the body text (never the injected sidebar), skips filler
    paragraphs shorter than 15 chars, and prefixes the page title.
    """
    title = extract_title(html, posixpath.basename(rel_path))
    # Never describe the page from the injected sidebar/audio blocks.
    body = strip_block(html, SIDEBAR_MARKER_START, SIDEBAR_MARKER_END)
    match = re.search(r"<main[^>]*>(.*?)</main>", body, re.DOTALL)
    if match:
        body = match.group(1)
    for para in re.findall(r"<p[^>]*>(.*?)</p>", body, re.DOTALL):
        text = re.sub(r"<[^>]+>", " ", para)
        text = htmlmod.unescape(text)
        # Sweep up any tag-like leftovers revealed by unescaping.
        text = re.sub(r"<[^>]*>", " ", text)
        text = re.sub(r"\s+", " ", text).strip()
        if len(text) >= 15:
            snippet = f"{title} - {text}" if title else text
            if len(snippet) > DESCRIPTION_MAX:
                snippet = snippet[: DESCRIPTION_MAX - 1].rstrip() + "…"
            return snippet
    return (title or posixpath.basename(rel_path))[:DESCRIPTION_MAX]


def collapse_head_blanks(html):
    """Collapse runs of blank lines inside <head>, outside <style> blocks.

    Removes the whitespace crumbs that older build versions left behind when
    replacing the meta description, without touching the hand-written CSS
    inside <style>.</style> tags.
    """
    match = re.search(r"<head[^>]*>(.*?)</head>", html, re.IGNORECASE | re.DOTALL)
    if not match:
        return html
    head = match.group(1)
    parts = re.split(r"(<style[^>]*>.*?</style>)", head, re.IGNORECASE | re.DOTALL)
    for i in range(0, len(parts), 2):
        parts[i] = re.sub(r"\n(?:[ \t]*\n)+", "\n\n", parts[i])
    return html[: match.start(1)] + "".join(parts) + html[match.end(1):]


def inject_meta_description(html, current_rel):
    """Replace any existing description meta tag with a generated one.

    Idempotent: every existing description tag is removed first and blank
    line crumbs left behind in the head are collapsed, then a single fresh
    tag is inserted after <title>.
    """
    # The old tag owns its whole line (newline + indentation), so removing
    # just the tag cannot leave whitespace crumbs that later passes would
    # treat as content and pad with more newlines.
    html = re.sub(r"\n?[ \t]*" + META_DESC_RE.pattern, "", html)
    html = collapse_head_blanks(html)
    description = PAGE_DESCRIPTIONS.get(
        current_rel, auto_description(html, current_rel)
    )
    meta = f'<meta name="description" content="{escape_attr(description)}">\n'
    match = re.search(r"</title>", html, re.IGNORECASE)
    if match:
        html = html[: match.end()] + "\n    " + meta + html[match.end():]
    elif "</head>" in html:
        html = html.replace("</head>", meta + "</head>", 1)
    else:
        html = meta + html
    return html


def inject_into_page(html, current_rel, sitemap):
    html = strip_block(html, CSS_MARKER_START, CSS_MARKER_END)
    html = strip_block(html, SIDEBAR_MARKER_START, SIDEBAR_MARKER_END)

    css_block = build_css_block(parent_dir(current_rel))
    if "</head>" in html:
        html = html.replace("</head>", css_block + "</head>", 1)
    else:
        html = css_block + html

    sidebar = build_sidebar(sitemap, current_rel)
    # Insert right after the <body> tag. Anchor it to </head> so the search
    # can never match a literal "<body>" inside inlined CSS or a comment.
    match = re.search(r"</head>\s*<body[^>]*>", html, re.IGNORECASE)
    if match:
        html = html[: match.end()] + sidebar + html[match.end():]
    else:
        match = re.search(r"<body[^>]*>", html, re.IGNORECASE)
        if match:
            html = html[: match.end()] + sidebar + html[match.end():]
        else:
            html = sidebar + html

    # Wrap the body text in the central cream text box (see style.css).
    html = wrap_content(html)

    # Per-page SEO meta description (curated map or auto-generated).
    html = inject_meta_description(html, current_rel)

    return normalize_marker_spacing(html)


# ---------------------------------------------------------------------------
# Markdown -> HTML conversion for content/.
#
# content/ holds the canonical source text of the digital garden as markdown.
# This section converts that tiny Markdown subset into HTML at build time, so
# the site stays plain static HTML + CSS: no JavaScript, no database, nothing
# runs in the browser. The converter is deliberately dependency-free (the
# standard library only) and lossless: every construct in content/ is one of
# these, and anything else is escaped and passed through verbatim, never
# rewritten.
#
# Subset supported (verified against every file in content/):
#   # Heading            -> <h1>
#   paragraphs           -> <p>, trailing double spaces become <br>
#   * bullet items       -> <ul>/<li> (flat, one item per line)
#   | pipe tables        -> <table> with <thead>/<tbody>
#   <https://...>        -> <a href="...">
# ---------------------------------------------------------------------------

AUTOLINK_RE = re.compile(r"<(https?://[^<>\s]+)>")


def inline_html(text):
    """Convert <url> autolinks to anchors and HTML-escape everything else.

    The text segments and the URL are handled separately so that escaping
    never mangles an <a href="..."> we just wrote.
    """
    parts = []
    pos = 0
    for match in AUTOLINK_RE.finditer(text):
        parts.append(escape_html(text[pos:match.start()]))
        url = match.group(1)
        parts.append(f'<a href="{escape_html(url)}">{escape_html(url)}</a>')
        pos = match.end()
    parts.append(escape_html(text[pos:]))
    return "".join(parts)


def split_table_row(line):
    """'| a | b |' -> ['a', 'b'] (whitespace trimmed, edge pipes dropped)."""
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|"):
        line = line[:-1]
    return [cell.strip() for cell in line.split("|")]


def is_separator_row(line):
    """True for a markdown table separator row like | --- | --- |."""
    cells = split_table_row(line)
    return bool(cells) and all(re.fullmatch(r":?-+:?", cell) for cell in cells)


def render_paragraph(lines):
    """A paragraph block; lines ending in 2+ spaces become <br> hard breaks.

    A hard break on the very last line of a block is dropped, matching
    Markdown: it would hang into an invisible end of paragraph.

    Each line is escaped/autolinked *before* the <br> is appended, so the
    escaping never turns our own break tag into literal "&lt;br&gt;" text.
    """
    out = []
    for i, line in enumerate(lines):
        hard_break = re.search(r"[ \t]{2,}$", line) is not None
        text = inline_html(line.rstrip())
        if hard_break and i < len(lines) - 1:
            out.append(text + "<br>")
        else:
            out.append(text)
    return " ".join(out)


def render_markdown_block(lines):
    """Render one blank-line-separated block of the source file."""
    first = lines[0].strip()

    # Heading: "# Title"
    if first.startswith("#"):
        return f"<h1>{inline_html(first[1:].strip())}</h1>"

    # Flat bullet list: every line starts with "* ".
    if all(line.startswith("* ") for line in lines):
        items = [f"<li>{inline_html(line[2:].strip())}</li>"
                 for line in lines]
        return "<ul>\n" + "\n".join(items) + "\n</ul>"

    # Pipe table: header row followed by a | --- | separator row.
    if (first.startswith("|") and len(lines) >= 2
            and is_separator_row(lines[1])):
        header = "".join(f"<th>{inline_html(c)}</th>"
                         for c in split_table_row(lines[0]))
        body_rows = []
        for line in lines[2:]:
            if not line.strip():
                continue
            cells = "".join(f"<td>{inline_html(c)}</td>"
                            for c in split_table_row(line))
            body_rows.append(f"<tr>{cells}</tr>")
        tbody = "\n".join(body_rows)
        return (f"<table>\n<thead><tr>{header}</tr></thead>\n"
                f"<tbody>\n{tbody}\n</tbody>\n</table>")

    # Plain paragraph (with hard breaks). render_paragraph already escapes
    # each line, so it must not pass through inline_html a second time.
    return f"<p>{render_paragraph(lines)}</p>"


def convert_markdown_to_html(md_text):
    """Convert one content file. Returns (title, body_html).

    The title comes from the first # heading; it also becomes the <title>
    and therefore the sidebar label for this page.
    """
    blocks = []
    current = []
    for line in md_text.splitlines():
        if line.strip():
            current.append(line)
        elif current:
            blocks.append(current)
            current = []
    if current:
        blocks.append(current)

    title = None
    for block in blocks:
        match = re.match(r"#\s+(.+)", block[0].strip())
        if match:
            title = match.group(1).strip()
            break

    body = "\n\n".join(render_markdown_block(block) for block in blocks)
    return title, body


def prettify_section(name):
    """'selected-works' -> 'Selected Works' (for folder landing pages)."""
    return name.replace("-", " ").replace("_", " ").title()


def skeleton_page(title, marker, body_html):
    """A bare page for the sidebar/CSS phase to inject into."""
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '    <meta charset="UTF-8">\n'
        '    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n'
        '    <meta name="viewport" content="width=device-width, '
        'initial-scale=1.0">\n'
        f"    <title>{escape_html(title)}</title>\n"
        "</head>\n"
        "<body>\n"
        f"<!-- {marker} -->\n"
        f"{body_html}\n"
        "</body>\n"
        "</html>"
    )


def write_generated(path, content, label):
    """Write a generated page; never overwrite a hand-written page."""
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if not GENERATED_RE.search(existing):
            print(f"  skipped {label}: {path} has no generated marker, "
                  "so it is treated as hand-written. Delete it or add the "
                  "marker to let the build own it.")
            return False
        if existing == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def generate_content_pages():
    """Phase 0: convert content/**/*.md into public/**/*.html.

    content/ stays the source of truth: edit the markdown, re-run the build,
    push. Also generates one landing page per folder (public/<folder>.html,
    mirroring technical.html) that lists its articles, and prunes generated
    pages whose markdown no longer exists so the two trees stay in sync.
    """
    if not CONTENT.is_dir():
        print(f"Note: no content folder at {CONTENT}; skipping markdown step.")
        return

    targets = set()    # rel html paths this run wants to exist under public/
    articles = []      # (html_rel, title) for the folder landing pages

    for md in sorted(CONTENT.rglob("*.md")):
        rel = md.relative_to(CONTENT).as_posix()
        html_rel = posixpath.splitext(rel)[0] + ".html"
        title, body = convert_markdown_to_html(
            md.read_text(encoding="utf-8"))
        if not title:
            title = prettify_section(md.stem)
        marker = (f"Generated by static_site_generator.py from content/{rel} - do not "
                  "edit by hand; edit the markdown and re-run static_site_generator.py.")
        targets.add(html_rel)
        articles.append((html_rel, title))
        out = PUBLIC / html_rel
        if write_generated(out, skeleton_page(title, marker, body), html_rel):
            print(f"  generated {html_rel}")

    # One landing page per folder that has articles, listed in the sidebar
    # as a section with its articles as children (like technical.html).
    for folder in sorted(d for d in CONTENT.iterdir() if d.is_dir()):
        section = folder.name
        children = [
            (rel, title) for rel, title in articles
            if rel.startswith(section + "/"
                              ) and "/" not in rel[len(section) + 1:]
        ]
        if not children:
            continue
        section_title = prettify_section(section)
        landing_rel = section + ".html"
        items = "\n".join(
            f'    <li><a href="{rel}">{escape_html(title)}</a></li>'
            for rel, title in sorted(children)
        )
        body = (f"<h1>{escape_html(section_title)}</h1>\n"
                f"<ul>\n{items}\n</ul>")
        marker = (f"Generated by static_site_generator.py from the content/{section}/ "
                  "folder - do not edit by hand; edit the markdown and "
                  "re-run static_site_generator.py.")
        targets.add(landing_rel)
        out = PUBLIC / landing_rel
        if write_generated(out, skeleton_page(section_title, marker, body),
                           landing_rel):
            print(f"  generated {landing_rel}")

    # Prune generated pages whose markdown or folder has been deleted.
    for html in sorted(PUBLIC.rglob("*.html")):
        rel = html.relative_to(PUBLIC).as_posix()
        if rel in targets:
            continue
        if GENERATED_RE.search(html.read_text(encoding="utf-8")):
            html.unlink()
            print(f"  pruned {rel} (source markdown is gone)")


def print_tree(nodes, indent=""):
    for node in nodes:
        if isinstance(node, PageNode):
            print(f"{indent}{node.rel_path}  ({node.label})")
            print_tree(node.children, indent + "  ")
        else:
            print(f"{indent}{node.label}/  (group)")
            print_tree(node.children, indent + "  ")


def main():
    generate_content_pages()
    sitemap = Sitemap()

    html_files = [p for p in sorted(PUBLIC.rglob("*.html"))
                  if not any(part in EXCLUDE_FROM_INJECTION
                             for part in p.relative_to(PUBLIC).parts[:-1])]
    if not html_files:
        print(f"No HTML files found under {PUBLIC}", file=sys.stderr)
        return 1

    print("Build step: sitemap:")
    print_tree(sitemap.root)

    for path in html_files:
        current_rel = path.relative_to(PUBLIC).as_posix()
        html = path.read_text(encoding="utf-8")
        updated = inject_into_page(html, current_rel, sitemap)
        if updated != html:
            path.write_text(updated, encoding="utf-8")
            print(f"  updated {path.name} ({current_rel})")
        else:
            print(f"  unchanged {path.name} ({current_rel})")

    print("Done. You can now git add, git commit, and git push.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())